name: Build and Push Updated Containers

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      # Set up Docker
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Detect changes
      - name: Detect changed Dockerfiles
        id: changes
        run: |
          echo "Checking for changed files..."
          # Detect changes in the <tool>/<version>/Dockerfile structure
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD | grep -E '^<tool>/.+/Dockerfile$' || true)
          echo "Changed files: $CHANGED_FILES"

          # Extract the directories containing changed Dockerfiles
          CHANGED_TOOLS=$(echo "$CHANGED_FILES" | sed -E 's|/Dockerfile$||' | uniq)
          echo "Changed tools: $CHANGED_TOOLS"

          # Export the list of changed tools
          echo "tools=$CHANGED_TOOLS" >> $GITHUB_ENV

      # Loop through changed tools and build their containers
      - name: Build and push Docker containers
        if: env.tools != ''
        run: |
          for TOOL in $tools; do
            echo "Building and pushing container for $TOOL..."
            TOOL_NAME=$(basename $TOOL)
            VERSION=$(basename $(dirname $TOOL))
            IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/${TOOL_NAME}:${VERSION}"
            docker buildx build --push -t $IMAGE_NAME $TOOL
          done

